"""Build a substitute-teacher packet — one PDF combining attendance,
seating chart, class roster sheet, and any custom notes / lesson plans.

Usage:
    python scripts/sub_packet.py --class Hamilton --to-inbox
    python scripts/sub_packet.py --class Hamilton \\
        --notes "Quiet reading 9-9:30. Math worksheets in red folder." \\
        --append lesson-plan.pdf agenda.pdf

What goes in the packet (in order):
    1. Cover page (class, date, sub name if provided, notes block)
    2. Attendance sheet
    3. Seating chart (5x6 grid by default)
    4. Roster list (Letter, two-column)
    5. Any extra PDFs passed via `--append`

Each section is generated by calling the matching helper script in
this folder, then concatenated with pypdf.

Dependencies:
    python -m pip install --user reportlab pypdf
"""

from __future__ import annotations

import argparse
import logging
import os
import re
from datetime import date, datetime
from pathlib import Path

log = logging.getLogger("printwatcher.sub_packet")


def _read_path_constant(text: str, name: str) -> Path | None:
    match = re.search(rf'{name}\s*=\s*Path\(r"([^"]+)"\)', text)
    if not match:
        return None
    raw = match.group(1)
    if "YOUR_USERNAME" in raw:
        return None
    return Path(raw)


def discover_inbox() -> Path:
    sibling = Path(__file__).resolve().parent.parent / "print_watcher_tray.py"
    if sibling.exists():
        try:
            text = sibling.read_text(encoding="utf-8", errors="ignore")
            inbox = _read_path_constant(text, "WATCH_DIR")
            if inbox is not None:
                return inbox
        except OSError:
            pass
    onedrive = (
        os.environ.get("OneDrive")
        or os.environ.get("OneDriveCommercial")
        or os.environ.get("OneDriveConsumer")
    )
    base = Path(onedrive) if onedrive else Path.home() / "OneDrive"
    return base / "PrintInbox"


_SLUG = re.compile(r"[^A-Za-z0-9._-]+")


def slugify(name: str) -> str:
    cleaned = _SLUG.sub("_", name.strip()).strip("._")
    return cleaned or "class"


def render_cover(
    class_name: str,
    target_date: date,
    sub_name: str | None,
    notes: str,
    output: Path,
) -> None:
    from reportlab.lib.pagesizes import letter
    from reportlab.pdfgen import canvas

    output.parent.mkdir(parents=True, exist_ok=True)
    page_w, page_h = letter
    c = canvas.Canvas(str(output), pagesize=letter)

    margin = 54
    y = page_h - margin

    c.setFont("Helvetica-Bold", 32)
    c.drawString(margin, y, "Substitute packet")
    y -= 36
    c.setFont("Helvetica-Bold", 20)
    c.drawString(margin, y, class_name)
    y -= 24
    c.setFont("Helvetica", 13)
    c.setFillGray(0.4)
    c.drawString(margin, y, target_date.strftime("%A, %B %d, %Y"))
    if sub_name:
        c.drawString(margin, y - 18, f"Substitute: {sub_name}")
        y -= 18
    c.setFillGray(0)
    y -= 38

    c.setFont("Helvetica-Bold", 13)
    c.drawString(margin, y, "What's in this packet")
    y -= 6
    c.setStrokeGray(0.85)
    c.line(margin, y, page_w - margin, y)
    y -= 16
    c.setFont("Helvetica", 11)
    for line in (
        "1. Cover page (this page)",
        "2. Attendance sheet",
        "3. Seating chart",
        "4. Roster list",
        "5. Any teacher-provided lesson plans / notes (appended)",
    ):
        c.drawString(margin + 8, y, line)
        y -= 16

    if notes:
        y -= 18
        c.setFont("Helvetica-Bold", 13)
        c.drawString(margin, y, "Teacher notes")
        y -= 6
        c.line(margin, y, page_w - margin, y)
        y -= 16
        c.setFont("Helvetica", 11)
        c.setFillGray(0.15)
        text_obj = c.beginText(margin + 8, y)
        text_obj.setFont("Helvetica", 11)
        text_obj.setLeading(15)
        wrap_width = page_w - 2 * margin - 16
        for paragraph in notes.split("\n"):
            words = paragraph.split(" ")
            line_buf = ""
            for word in words:
                candidate = (line_buf + " " + word).strip() if line_buf else word
                if c.stringWidth(candidate, "Helvetica", 11) <= wrap_width:
                    line_buf = candidate
                else:
                    text_obj.textLine(line_buf)
                    line_buf = word
            if line_buf:
                text_obj.textLine(line_buf)
            text_obj.textLine("")
        c.drawText(text_obj)
        c.setFillGray(0)

    # Footer
    c.setFillGray(0.55)
    c.setFont("Helvetica", 8)
    c.drawString(margin, margin / 2,
                 f"PrintWatcher · {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    c.showPage()
    c.save()


def merge_pdfs(parts: list[Path], output: Path) -> int:
    from pypdf import PdfReader, PdfWriter

    output.parent.mkdir(parents=True, exist_ok=True)
    writer = PdfWriter()
    pages = 0
    for path in parts:
        if not path.exists():
            log.warning("missing component %s, skipping", path)
            continue
        try:
            reader = PdfReader(str(path))
        except Exception as exc:
            log.warning("could not read %s: %s", path.name, exc)
            continue
        for page in reader.pages:
            writer.add_page(page)
            pages += 1
    with output.open("wb") as fh:
        writer.write(fh)
    return pages


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--class", dest="classname", required=True)
    parser.add_argument("--csv", type=Path, default=None)
    parser.add_argument("--date", default=None,
                        help="YYYY-MM-DD (default: today)")
    parser.add_argument("--sub-name", default=None,
                        help="substitute teacher name on the cover")
    parser.add_argument("--notes", default="",
                        help="freeform teacher notes; use \\n for newlines")
    parser.add_argument("--rows", type=int, default=5,
                        help="seating chart rows (default 5)")
    parser.add_argument("--cols", type=int, default=6,
                        help="seating chart columns (default 6)")
    parser.add_argument("--seating", choices=("random", "alphabetical"),
                        default="alphabetical",
                        help="seating arrangement (default alphabetical)")
    parser.add_argument("--seed", type=int, default=None)
    parser.add_argument("--append", type=Path, nargs="*", default=[],
                        help="extra PDFs to append (lesson plans, etc.)")
    parser.add_argument("--out", type=Path, default=None)
    parser.add_argument("--to-inbox", action="store_true")
    args = parser.parse_args(argv)

    logging.basicConfig(level=logging.INFO, format="%(message)s")

    target_date = date.fromisoformat(args.date) if args.date else date.today()

    # Import sibling helpers; they are also available as submodules of
    # this package when installed as part of PrintWatcher.
    try:
        from . import attendance_sheet, seating_chart, roster as roster_module
    except ImportError:
        # Standalone invocation (e.g. `python scripts/sub_packet.py`)
        import importlib.util
        here = Path(__file__).resolve().parent

        def _load(name: str):
            spec = importlib.util.spec_from_file_location(name, here / f"{name}.py")
            module = importlib.util.module_from_spec(spec)
            assert spec.loader is not None
            spec.loader.exec_module(module)
            return module

        attendance_sheet = _load("attendance_sheet")
        seating_chart = _load("seating_chart")
        roster_module = _load("roster")

    inbox = discover_inbox() if args.to_inbox else None
    output = (
        inbox / f"sub-packet-{slugify(args.classname)}-{target_date.isoformat()}.pdf"
        if inbox else (args.out or Path.cwd() /
                       f"sub-packet-{slugify(args.classname)}-{target_date.isoformat()}.pdf")
    )

    work_dir = output.parent / f".{output.stem}-parts"
    work_dir.mkdir(parents=True, exist_ok=True)

    cover_pdf = work_dir / "01-cover.pdf"
    attendance_pdf = work_dir / "02-attendance.pdf"
    seating_pdf = work_dir / "03-seating.pdf"
    roster_pdf = work_dir / "04-roster.pdf"

    try:
        render_cover(args.classname, target_date, args.sub_name, args.notes, cover_pdf)
        attendance_sheet.main([
            "--class", args.classname,
            *(["--csv", str(args.csv)] if args.csv else []),
            "--date", target_date.isoformat(),
            "--out", str(attendance_pdf),
        ])
        seating_chart.main([
            "--class", args.classname,
            *(["--csv", str(args.csv)] if args.csv else []),
            "--rows", str(args.rows),
            "--cols", str(args.cols),
            f"--{args.seating}",
            *(["--seed", str(args.seed)] if args.seed is not None else []),
            "--date", target_date.isoformat(),
            "--out", str(seating_pdf),
        ])
        roster_module.main([
            "sheet", args.classname,
            *(["--csv", str(args.csv)] if args.csv else []),
            "--out", str(roster_pdf),
        ])
    except SystemExit as exc:
        if exc.code not in (0, None):
            log.error("section build failed (exit %s)", exc.code)
            return int(exc.code) if isinstance(exc.code, int) else 1

    parts = [cover_pdf, attendance_pdf, seating_pdf, roster_pdf]
    parts.extend(p for p in args.append if p.exists())

    try:
        pages = merge_pdfs(parts, output)
    except ImportError:
        log.error("pypdf required: `python -m pip install --user pypdf reportlab`")
        return 2

    # Cleanup intermediates
    for p in (cover_pdf, attendance_pdf, seating_pdf, roster_pdf):
        try:
            p.unlink()
        except OSError:
            pass
    try:
        work_dir.rmdir()
    except OSError:
        pass

    log.info("wrote %s (%d page(s))", output, pages)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
